services:
  telegram-bot-api:
    image: ghcr.io/avbor/docker-telegram-bot-api:latest
    restart: unless-stopped
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    environment:
      - TELEGRAM_API_ID=
      - TELEGRAM_API_HASH=
    ports:
      - 8081:8081
      - 127.0.0.1:8082:8082
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081 >/dev/null || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    command:
      --local
      --http-port=8081
      --http-stat-port=8082
      --dir=/var/lib/telegram-bot-api
      --temp-dir=/var/lib/telegram-bot-api/temp
      --verbosity=1

volumes:
  telegram-bot-api-data:
